version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.5
        environment:
          MIX_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      # cache is not used since yamler is recompiled every time
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run: mix do deps.get, compile

      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths: deps
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: deps
      - save_cache:
          key: v1-mix-cache
          paths: deps
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: _build
      - save_cache:
          key: v1-build-cache
          paths: _build

      - run: mix test
